# fly.toml app configuration file generated for pdf-booklet-tools on 2025-02-05T15:00:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdf-booklet-tools"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "den"

[build]
dockerfile = "Dockerfile"

[env]
APP_ENV = "production"
PORT = "8080"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[[services]]
internal_port = 8_080
processes = [ "app" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 10
  soft_limit = 5
  type = "connections"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
